api_host = [0, 0, 0, 0] # Address 0.0.0.0 (meaning all IP4 addresses on the local machine) required when operating within a container to be accessed.
api_port = 3030
database_host = "172.20.0.5"
database_name = "contacts"
database_password = "pw"
database_port = 5432
database_user = "postgres"
log_file_name = "contact-api.log"
log_level_api = "info"
log_level_handle_errors = "info"
log_level_warp = "error"
log_path_name = "/tmp"

