api_host = [127, 0, 0, 1]
api_port = 3030
database_host = "localhost"
database_name = "contacts"
database_password = "pw"
database_port = 5432
database_user = "postgres"
log_file_name = "contact-api.log"
log_level_api = "info"
log_level_warp = "error"
log_path_name = "/tmp"
